version: "3.8"
services:
  blog_app:
    container_name: app_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./src/:/usr/src/app
      - ./src/public:/usr/src/app/public
    depends_on:
      - blog_db
    networks:
      - app_network

  blog_nginx:
    container_name: app_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./src/public:/usr/src/app/public
    ports:
      - "8989:80"
    depends_on:
      - blog_app
    environment:
      NGINX_FPM_HOST: blog_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  blog_db:
    container_name: app_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3388:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge